"""seeds

Revision ID: b5d339ba1d48
Revises: 5f84e81951a1
Create Date: 2022-04-26 22:48:45.107121

"""
from datetime import datetime

import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy import DateTime, String, table

from alembic import op

revision = "b5d339ba1d48"
down_revision = "5f84e81951a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    "34a52148-64fe-4cc8-af37-624aba5909a9"

    customer = table(
        "customer",
        sa.Column("id", String),
        sa.Column("name", String),
        sa.Column("created_at", DateTime),
    )

    category = table(
        "category",
        sa.Column("id", String),
        sa.Column("name", String),
        sa.Column("created_at", DateTime),
    )

    op.bulk_insert(
        customer,
        [
            {
                "id": "34a52148-64fe-4cc8-af37-624aba5909a9",
                "name": "Paulinho Julinho",
                "created_at": datetime.now(),
            },
        ],
    )

    op.bulk_insert(
        category,
        [
            {
                "id": "00e88809-e3df-4e6a-9351-9c74b239649b",
                "name": "Serviços Automotivos",
                "created_at": datetime.now(),
            },
            {
                "id": "224e56e6-0c88-4a3d-b05c-f349ebd5f187",
                "name": "Vestuário",
                "created_at": datetime.now(),
            },
            {
                "id": "d71ae545-2c66-4342-aa60-7a77fb6b97bb",
                "name": "Postos de Gasolina",
                "created_at": datetime.now(),
            },
            {
                "id": "3d9ac3f3-810b-4d87-84f9-744ed8e9d395",
                "name": "Supermercado",
                "created_at": datetime.now(),
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
