"""seeds

Revision ID: c770dda9dc58
Revises: eb581a2d3141
Create Date: 2022-04-27 22:02:36.312882

"""
from datetime import datetime

import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy import DateTime, String, table

from alembic import op

revision = "c770dda9dc58"
down_revision = "eb581a2d3141"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    customer = table(
        "customer",
        sa.Column("id", String),
        sa.Column("name", String),
        sa.Column("created_at", DateTime),
    )

    category = table(
        "category",
        sa.Column("id", String),
        sa.Column("name", String),
        sa.Column("created_at", DateTime),
    )

    op.bulk_insert(
        customer,
        [
            {
                "id": "34a52148-64fe-4cc8-af37-624aba5909a9",
                "name": "Paulinho Julinho",
                "created_at": datetime.now(),
            },
            {
                "id": "17d16d56-4802-43fb-a502-0cd504ec4523",
                "name": "Julinho Paulinho",
                "created_at": datetime.now(),
            },
        ],
    )

    op.bulk_insert(
        category,
        [
            {
                "id": "00e88809-e3df-4e6a-9351-9c74b239649b",
                "name": "Serviços Automotivos",
                "created_at": datetime.now(),
            },
            {
                "id": "224e56e6-0c88-4a3d-b05c-f349ebd5f187",
                "name": "Vestuário",
                "created_at": datetime.now(),
            },
            {
                "id": "d71ae545-2c66-4342-aa60-7a77fb6b97bb",
                "name": "Postos de Gasolina",
                "created_at": datetime.now(),
            },
            {
                "id": "3d9ac3f3-810b-4d87-84f9-744ed8e9d395",
                "name": "Supermercado",
                "created_at": datetime.now(),
            },
            {
                "id": "3f1dbe6b-fddd-40e6-bfc4-aaf6e6cda430",
                "name": "Categoria muito suspeita",
                "created_at": datetime.now(),
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
